xcat-inventory/xcclient/inventory/dbfactory.py

```
[root@c910f03c05k21 ~]# cat /tmp/node0009 |grep consoleenabled
"consoleenabled": "11"
[root@c910f03c05k21 ~]# xcat-inventory import -f /tmp/node0009
Importing object: node0009
Error: no column 'mconsoleenabled' in table nodehm, might caused by mismatch between schema version and xCAT version!
[root@c910f03c05k21 ~]# echo $?
1
[root@c910f03c05k21 ~]# xcat-inventory import -f /tmp/node0009
Importing object: node0009
Importing object: xcatdefaults
```

only abort on error when the invaid column is used in inventory file

---

README.md
xcat-inventory/xcclient/inventory/dbobject.py
xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/schema/1.0/zone.yaml

```
[root@c910f03c05k21 xCAT-Incubator]# xcat-inventory export -t zone
{
"schema_version": "1.0",
"zone": {
"aa": {
"defaultzone": "no",
"sshbetweennodes": "yes",
"sshkeydir": "/etc/xcat/sshkeys/aa/.ssh"
},
"xcatdefault": {
"defaultzone": "yes",
"sshbetweennodes": "yes",
"sshkeydir": "/root/.ssh"
}
}
}
[root@c910f03c05k21 xCAT-Incubator]# xcat-inventory import -f /tmp/zones
Importing object: aa
Importing object: xcatdefault
```

add zone support

---

xcat-inventory/xcclient/inventory/xcatobj.py

```
[root@c910f03c05k21 xCAT-Incubator]# xcat-inventory export -t zone
{
"schema_version": "1.0",
"zone": {
"aa": {
"defaultzone": "no",
"sshbetweennodes": "yes",
"sshkeydir": "/etc/xcat/sshkeys/aa/.ssh"
},
"xcatdefault": {
"defaultzone": "yes",
"sshbetweennodes": "yes",
"sshkeydir": "/root/.ssh"
}
}
}
```

add Zone class

---

xcat-inventory/xcclient/inventory/schema/1.0/route.yaml

```
[root@c910f03c05k21 1.0]# cat /tmp/routes
{
"route": {
"gw_def": {
"gateway": "10.3.5.21",
"ifname": "eth0",
"mask": "0.0.0.0",
"net": "1.1.1.1"
},
"default": {
"gateway": "10.3.5.21",
"ifname": "eth0",
"mask": "0.0.0.0",
"net": "default"
}
},
"schema_version": "1.0"
}
[root@c910f03c05k21 1.0]# xcat-inventory import -f /tmp/routes
Importing object: gw_def
Importing object: default
```

fix route.net validation: net might be default

---

xcat-inventory/xcclient/inventory/schema/1.0/network.yaml

UT:
```
[root@c910f03c05k21 1.0]# xcat-inventory export -t network  >/tmp/network
[root@c910f03c05k21 1.0]# xcat-inventory import -f /tmp/network
Importing object: hpctest3
Importing object: management
Importing object: 50_0_0_0-255_0_0_0
Importing object: 192_168_122_0-255_255_255_0
Importing object: 192_168_11_0-255_255_255_0
```

network object validation: gateway can be hostname,range can be single ip address

---

xcat-inventory/xcclient/inventory/dbfactory.py
xcat-inventory/xcclient/inventory/schema/1.0/node.yaml

UT:
```
[root@boston02 inventory]# cat /tmp/faketest
{
"node": {
"faketest": {
"device_info": {
"arch": "armv7l",
"characteristics": "switch"
},
"device_type": "switch",
"engines": {
"hardware_mgt_engine": {
"engine_type": "switch"
}
},
"network_info": {
"otherinterfaces": "172.21.208.3",
"primarynic": {
"ip": "172.21.208.13",
"mac": [
"8c:ea:1b:e8:78:c0"
],
"switch": "mid08",
"switchport": "3"
}
},
"obj_type": "node",
"obj_info": {
"groups": "all",
},
"role": "service"
}
},
"schema_version": "1.0"
}
[root@boston02 inventory]# xcat-inventory import -f  /tmp/faketest
Importing object: faketest
[root@boston02 inventory]# xcat-inventory export -t node -o faketest
{
"node": {
"faketest": {
"device_info": {
"arch": "armv7l",
"characteristics": "switch"
}, …
```

remove duplicate table entries in node template; refine code logic to remove table entries while importing

---

xcat-inventory/xcclient/inventory/vutil.py

UT:
```
[root@boston02 inventory]# cat /tmp/cluster|grep '172.21.208.03'
"ip": "172.21.208.03",
[root@boston02 inventory]# xcat-inventory import -f  /tmp/cluster
...
[root@boston02 inventory]# xcat-inventory export -t node -o mid08tor03
{
"node": {
"mid08tor03": {
"device_info": {
"arch": "armv7l",
"characteristics": "switch",
"switchtype": "onie"
},
"device_type": "switch",
"engines": {
"hardware_mgt_engine": {
"engine_type": "switch"
}
},
"network_info": {
"otherinterfaces": "172.21.208.3",
"primarynic": {
"ip": "172.21.208.03",
"mac": [
"8c:ea:1b:e8:78:c0"
],
"switch": "mid08",
"switchport": "3"
}
},
"obj_info": {
"description": "Cumulus Linux 3.5.2 (Linux Kernel 4.1.33-1+cl3u11)",
"groups": "switch,edge_switch"
},
"obj_type": "node",
"role": "compute"
} …
```

correct ip address validation, take ip address with leading zero as legal

---

xcat-inventory/xcclient/inventory/schema/1.0/network.yaml
xcat-inventory/xcclient/inventory/schema/1.0/node.yaml
xcat-inventory/xcclient/inventory/schema/1.0/route.yaml

UT:
```
[root@c910f03c05k21 inventory]# xcat-inventory import -f /tmp/node0008
Importing object: node0008
[root@c910f03c05k21 inventory]# xcat-inventory import -f /tmp/routes
Error: failed to validate attribute [net] of object "autotestnet", criteria: "value='': True if vutil.isIPaddr(value) or value in ['default'] else False"
[root@c910f03c05k21 inventory]# xcat-inventory import -f /tmp/cluster -t osimage
Importing object: test1
Importing object: sles12.2-ppc64le-install-compute
Importing object: rhels7.4-ppc64le-netboot-compute
Importing object: rhels7.4-x86_64-install-compute
Importing object: sles12.2-ppc64le-statelite-compute
Importing object: rhels6.4-ppc64le-install-compute
Importing object: sles12.2-ppc64le-netboot-compute
Importing object: …
```

refine schema, use [] instead of ()

---

xcat-inventory/debian/install

UT:
1, build deb package: ./build-ubuntu -c xcat-inventory
2, check deb package:
```
dpkg-deb -c xcat-inventory_0.1.1-snap201804032323_all.deb
```
3, install and run `xcat-inventory export`, print correct result.

enhance xcat-inventory deb pkg

---

xcat-inventory/xcclient/shell.py

To fix https://github.com/xcat2/xcat-inventory/issues/19
UT:
```
usage: xcat-inventory [-h] [--debug] [-v] [-V] <subcommand> ...
xCAT inventory management tool
Positional arguments:
<subcommand>
export       Export the inventory data from xcat database
help         Display help about this program or one of its subcommands.
import       Import inventory file to xcat database
Optional arguments:
-h, --help     Prints help message
--debug        Prints debugging output into the log file (not implemented
yet).
-v, --verbose  Prints verbose output (not implemented yet).
-V, --version  Shows the program version and exits.
See "xcat-inventory help COMMAND" for help on a specific command.
usage: xcat-inventory export [-t <type>] [-o <name>] [-f <path>]
[-s <version>] [--format <format>]
Export …
```

Fix the issue to print help message

---

xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/shell.py

To address #18 
Introduce `-x|--exclude` to exclude some types when export all.
UT:
```
xcat-inventory help export
usage: xcat-inventory export [-t <type>] [-x EXCLUDE] [-o <name>] [-f <path>]
[-s <version>] [--format <format>]
Export the inventory data from xcat database
Arguments:
-t <type>, --type <type>
type of objects to export, valid values:
node,network,passwd,route,site,osimage,policy. If not
specified, all objects in xcat databse will be
exported
-x EXCLUDE, --exclude EXCLUDE
types to be excluded when exporting all, delimited
with Comma(,).
-o <name>, --objects <name>
names of the objects to export, delimited with
Comma(,). If not specified, all objects of the
specified type will be exported
-f <path>, --path <path>
path of the inventory file(not implemented yet)
-s <version>, …
```

Separate out source control for osimage #18

---

xcat-inventory/debian/dirs

#29 
After fix, UT:
```
root@c910f03c05k10:~/level0/level1/level2/xcat-inventory# ./build-ubuntu -c
###############################
###############################
............
dpkg-deb: building package 'xcat-inventory' in '../xcat-inventory_0.1.2-snap201805150113_all.deb'.
pwd
/root/level0/level1/level2/xcat-inventory/xcat-inventory
dpkg-genchanges  >../xcat-inventory_0.1.2-snap201805150113_ppc64el.changes
dpkg-genchanges: warning: the current version (0.1.2-snap201805150113) is earlier than the previous one (2.9.13-1)
dpkg-genchanges: including full source code in upload
dpkg-source --after-build xcat-inventory
dpkg-buildpackage: full upload; Debian-native package (full source is included)
/root/level0/level1/level2/xcat-inventory …
```

fix debian packaging error

---

xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/schema/1.0/node.yaml
xcat-inventory/xcclient/inventory/schema/1.0/osimage.yaml
xcat-inventory/xcclient/inventory/shell.py
xcat-inventory/xcclient/inventory/vutil.py
xcat-inventory/xcclient/inventory/xcatobj.py

design:
https://github.com/xcat2/xcat-core/wiki/the-mini-design-of-xcat-inventory-export-and-import-for-osimage
for task:
https://github.com/xcat2/xcat2-task-management/issues/128
enhancements:
*  `-t|--type` can be comma delimited types
```
[root@c910f03c05k21 inventory]# xcat-inventory export -t osimage,zone,passwd 
[root@c910f03c05k21 inventory]# xcat-inventory import -t osimage,zone,passwd -f /tmp/cluster
```
*  export(dump) inventory data to a file:
```
[root@c910f03c05k21 inventory]# xcat-inventory export -t osimage,zone,passwd -f /tmp/cluster
```
* export cluster inventory data to a cluster inventory directory:
```
[root@c910f03c05k21 inventory]# xcat-inventory export -d /tmp/mm/
...
Warning: The file "/install/templates/compute/compute.tmpl" of osimage object "compute" does not …
```

enhance xcat-inventory export/import for osimage

---

xcat-inventory/xcclient/inventory/manager.py

* refine the message format to more pythonic; 
* add dryrun support for import
UT:
```
[root@c910f03c05k21 xCAT-Incubator]# xcat-inventory import -d /tmp/mm/osimage/rhels7.4-ppc64le-install-compute  --dry
Importing object: rhels7.4-ppc64le-install-compute
Dry run mode, nothing will be written to database!
creating directory: /tmp. Dryrun mode, do nothing...
copying file: /tmp/mm/osimage/rhels7.4-ppc64le-install-compute/tmp/synclists ----> /tmp/synclists. Dryrun mode, do nothing...
The object rhels7.4-ppc64le-install-compute has been imported
[root@c910f03c05k21 xCAT-Incubator]# lsdef -t osimage -o rhels7.4-ppc64le-install-compute
Error: Could not find an object named 'rhels7.4-ppc64le-install-compute' of type 'osimage'.
[root@c910f03c05k21 xCAT-Incubator]# ls /tmp/synclists
ls: cannot …
```

refine the message format to more pythonic; add dryrun support for import

---

xcat-inventory/xcclient/inventory/manager.py

UT:
```
[root@c910f03c05k21 inventory]# xcat-inventory export -t osimage -o rhels7.4-ppc64le-install-service  -d /tmp/kkk/mmm/nnn
Error: the specified directory /tmp/kkk/mmm/nnn does not exist!
[root@c910f03c05k21 inventory]# xcat-inventory export -f /tmp/aaa/
Error: /tmp/aaa/ is not a file!
```

add more strict check on -f|--path

---

xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/utils.py

for issue https://github.com/xcat2/xcat-inventory/issues/35
* add xcat version in exported definition 
UT:
```
[root@c910f03c05k21 xcclient]# xcat-inventory export -t osimage -o compute --format yaml
osimage:
compute:
basic_attributes:
arch: ppc64le
distribution: rhels6.4
osdistro: rhels7.3-ppc64le
osname: linux
imagetype: linux
package_selection:
otherpkglist: /install/templates/compute/myotherpkglist
pkgdir: /install/rhels7.3/x86_64,/install/software/otherpkgs,/install/software/saltstack,/install/software/epel,/install/software/rhel-7-server,/install/software/rhel-7-server-optional-rpms
pkglist: /opt/xcat/share/xcat/install/rh/compute.rhels7.pkglist
provision_mode: install
role: compute
template: /install/templates/compute/compute.tmpl
schema_version: '1.0'
#Version 2.14.1 (git commit …
```

add xcat version in exported definition

---

xcat-inventory/xcclient/inventory/manager.py

set the default format to json in export_by_type
UT:
before this fix:
```
[root@c910f03c05k21 templates]# xcat-inventory export -t osimage -o test_myimage -d /opt/xcat/share/xcat/tools/autotest/testcase/xcat-inventory/templates/
The osimage objects has been exported to directory /opt/xcat/share/xcat/tools/autotest/testcase/xcat-inventory/templates/
[root@c910f03c05k21 templates]# tree /opt/xcat/share/xcat/tools/autotest/testcase/xcat-inventory/templates/test_myimage/
/opt/xcat/share/xcat/tools/autotest/testcase/xcat-inventory/templates/test_myimage/
├── definition.yaml
└── tmp
├── exlist
├── otherpkglist
├── partitionfile
├── postinstall
└── synclists
1 directory, 6 files
[root@c910f03c05k21 templates]# cat /opt/xcat/share/xcat/tools/autotest/testcase/xcat-inventory/templates/test_myimage/ …
```

set the default format to json in export_by_type

---

xcat-inventory/xcclient/inventory/vutil.py

fix https://github.com/xcat2/xcat-inventory/issues/47:
UT:
```
[root@boston02 xcclient]# xcat-inventory export -t osimage -o test_osimage -d /tmp/imagedata/export
The osimage objects has been exported to directory /tmp/imagedata/export
[root@boston02 xcclient]#
```

fix [FVT]:xcat-inventory export osimage could not find correct file #47

---

xcat-inventory/debian/control
xcat-inventory/requirements.txt
xcat-inventory/xcat-inventory.spec
xcat-inventory/xcclient/inventory/exceptions.py
xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/schema/1.0/osimage.yaml
xcat-inventory/xcclient/inventory/shell.py
xcat-inventory/xcclient/inventory/utils.py
xcat-inventory/xcclient/inventory/xcatobj.py

for feature https://github.com/xcat2/xcat-inventory/issues/44:
UT:
the git directory `/git/xcat_clusters` is a fork from repo https://github.ibm.com/yangsbj/xcat_clusters, the osimage inventory file  `ist.redhat.perf.custom.netboot.DL.osimage.yaml` includes 2 environment variables:
* {{GITREPO}}: the path to the git dir. if the environment variable `GITREPO` does not exist, will detect the git root directory of the specified inventory file `ist.redhat.perf.custom.netboot.DL.osimage.yaml`
* {{SWDIR}}: the path to the shared SW directory. if the environment variable `SWDIR `  does not exist, will take `/install/REPO` as default value
```
[root@c910f03c05k21 rhels]# pwd
/git/xcat_clusters/osimage/rhels
[root@c910f03c05k21 rhels]# cat ./ist.redhat.perf.custom.netboot.DL.osimage.yaml
osimage: …
```

support environment variables in osimage inventory data and files

---

xcat-inventory/xcclient/inventory/manager.py

remove the default value of variable `SWDIR `
```
[root@c910f03c05k21 xCAT-Incubator]# xcat-inventory import -f /home/yangsbj/xcat_clusters/osimage/rhels/ist.redhat.perf.custom.netboot.DL.osimage.yaml
unresolved variables in "/home/yangsbj/xcat_clusters/osimage/rhels/ist.redhat.perf.custom.netboot.DL.osimage.yaml": "SWDIR", please export them in environment variables
```

remove the default value for variable SWDIR

---

xcat-inventory/xcclient/inventory/manager.py

* fix a issue to use relative path for -f without prefix directory
UT:
before fix:
```
[root@c910f03c05k21 xCAT-Incubator]# xcat-inventory import -f README.md
Traceback (most recent call last):
File "/opt/xcat/lib/python/xcclient/inventory/shell.py", line 62, in main
InventoryShell('xcat-inventory','0.1.4 (git commit 2ac4ede95e6a8509a7236a418c8c310c9ad30289)').run(sys.argv[1:], '1.0', "xCAT inventory management tool")
File "/opt/xcat/lib/python/xcclient/shell.py", line 193, in run
return args.func(args)
File "/opt/xcat/lib/python/xcclient/inventory/shell.py", line 45, in do_import
mgr.importobj(args.path,args.directory,args.type,args.name,dryrun=args.dryrun,version=args.version,update=args.update)
File "/opt/xcat/lib/python/xcclient/inventory/manager.py", line 476, in importobj …
```

* remove the default value for variable SWDIR

---

xcat-inventory/xcclient/inventory/schema/1.0/osimage.yaml
xcat-inventory/xcclient/inventory/vutil.py
xcat-inventory/xcclient/inventory/xcatobj.py

with this feature, the substring in `otherpkgdir`, `otherpkglist`, `pkgdir`,  `pkglist` , `postinstall` 
`environvar`,`synclists`,`rootimgdir `,`partitionfile`,`template` attributes are replaced with the environment variables in `environvar`
UT:
```
[root@c910f03c05k21 xCAT-Incubator]# lsdef -t osimage -o ist.redhat.perf.custom.netboot.DL
Object name: ist.redhat.perf.custom.netboot.DL
environvar=GITREPO=/tmp,SWDIR=/install/swrepo
imagetype=linux
osarch=ppc64le
osdistroname=rhels7.5-ppc64le
osname=Linux
osvers=rhels7.5
otherpkgdir=/install/swrepo/software
otherpkglist=/tmp/osimage/rhels/common/otherpkglist/essl.otherpkglist,/tmp/osimage/rhels/common/otherpkglist/pessl.otherpkglist,/tmp/osimage/rhels/common/otherpkglist/xlc.otherpkglist,/tmp/osimage/rhels/common/otherpkglist/xlf.otherpkglist …
```

support osimage export with environvars

---

xcat-inventory/xcclient/inventory/schema/1.0/osimage.yaml
xcat-inventory/xcclient/inventory/xcatobj.py

fix issue https://github.com/xcat2/xcat-inventory/issues/52:
UT:
```
[root@boston02 xcat-inventory]# xcattest -t export_import_osimage_with_INCLUDE_in_file
xCAT automated test started at Thu Jun 28 05:02:46 2018
******************************
To detect current test environment
******************************
Detecting: OS = linux
Warning: No compute node defined, can't get ARCH of compute node
Warning: No compute node defined, can't get HCP TYPE of compute node
******************************
loading test cases
******************************
To run:
export_import_osimage_with_INCLUDE_in_file
******************************
Start to run test cases
******************************
------START::export_import_osimage_with_INCLUDE_in_file::Time:Thu Jun 28 05:02:46 2018------ …
```

fix issue [FVT]xcat-inventory import could not save files when the files are included in osimage defintion. #52

---

xcat-inventory/xcclient/inventory/manager.py

fix https://github.com/xcat2/xcat-inventory/issues/59:
UT:
```
[root@boston02 inventory]# xcat-inventory import -t osimage -d /tmp/export
Importing object: test_osimage
Warning: the /tmp/imagedata/test_osimage/file4.2 already exists, will be overwritten
Warning: the /tmp/imagedata/test_osimage/file4.1 already exists, will be overwritten
Warning: the /tmp/imagedata/test_osimage/file4.3 already exists, will be overwritten
Warning: the /tmp/imagedata/test_osimage/pkglist already exists, will be overwritten
Warning: the /tmp/imagedata/test_osimage/exlist already exists, will be overwritten
Warning: the /tmp/imagedata/test_osimage/file1.1 already exists, will be overwritten
Warning: the /tmp/imagedata/test_osimage/file6 already exists, will be overwritten …
```

fix issue [FVT]:xcat-inventory import could not import all osimages when there is files under the import directory #59

---

xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/shell.py

UT:
```
RUN:xcat-inventory import -f /opt/xcat/share/xcat/tools/autotest/testcase/xcat-inventory/templates/environment/test.environments.osimage.update.json -e GITREPO=/opt/xcat/share/xcat/tools/autotest/testcase/xcat-inventory/templates/environment/gitrepo -e SWDIR=/opt/xcat/share/xcat/tools/autotest/testcase/xcat-inventory/templates/environment/swdir [Wed Jul 11 03:28:34 2018]
ElapsedTime:1 sec
RETURN rc = 0
OUTPUT:
Importing object: test.environments.osimage
CHECK:output =~ Importing object: test.environments.osimage     [Pass]
CHECK:output =~ Inventory import successfully!  [Pass]
CHECK:rc == 0   [Pass]
```
lsdef:
```
Object name: test.environments.osimage
environvar=GITREPO=/opt/xcat/share/xcat/tools/autotest/testcase/xcat-inventory/templates/environment …
```

Add -e option for environment variables

---

xcat-inventory/xcclient/inventory/xcatobj.py

fix  https://github.com/xcat2/xcat-inventory/issues/72:
UT:
```
[root@stratton01 ~]# xcat-inventory export -t node -o group1
{
"node": {
"group1": {
"device_type": "server",
"network_info": {
"nics": {
" eno2": {
"networks": [
"net-infra"
]
},
" eno5": {
"networks": [
"pub-yellow"
],
"type": [
"ethernet"
]
},
"eno1": {
"hostnamesuffixes": [
"-compute"
],
"networks": [
"xcat-compute"
],
"type": [
"ethernet"
]
},
"eno2": {
"hostnamesuffixes": [
"-net-infra"
]
},
"eno3": {
"hostnamesuffixes": [
"-pdu"
],
"networks": [
"pdu"
],
"type": [
"ethernet"
]
},
"eno4": {
"hostnamesuffixes": [
"-bmc"
],
"networks": [
"bmc"
],
"type": [
"ethernet"
]
},
"eno5": {
"hostnamesuffixes": [
"-yellow"
]
}
}
},
"obj_type": "group",
"role": "compute"
}
},
"schema_version": "1.0"
}
#Version 2.14.3 (git commit …
```

fix xcat-inventory export failed when some fields in nics table is blank #72

---

xcat-inventory/xcclient/inventory/exceptions.py
xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/shell.py
xcat-inventory/xcclient/inventory/xcatobj.py

this PR is for feature request https://github.com/xcat2/xcat-inventory/issues/66:
1. add a new object type `credential`
2. the credential object contain the xcatd SSL CA certificate, private key, root's client SSL credential and server side SSL certificate
```
[root@c910f03c05k21 inventory]# xcat-inventory export -t credential
{
"credential": {
"credential": {
"CA": {
"certificate": "/etc/xcat/ca/ca-cert.pem",
"private_key": "/etc/xcat/ca/private/ca-key.pem"
},
"client": {
"root": "/root/.xcat/client-cred.pem"
},
"server": "/etc/xcat/cert/server-cred.pem"
}
},
"schema_version": "1.0"
}
#Version 2.14.3 (git commit d74f1eed53ef385d80a9013d46c2a7cff1de06e4, built Wed Jul 18 06:15:52 EDT 2018)
```
3. `xcat-inventory export -d` can be used to export the definition file and the credential files …

support credential export/import

---

xcat-inventory/xcclient/inventory/schema/1.0/osimage.yaml

fix https://github.com/xcat2/xcat-inventory/issues/80:
UT:
for osimage definition:
```
[root@c910f03c05k21 1.0]# lsdef -t osimage -o ist.redhat-alt.perf.custom.install.DF
Object name: ist.redhat-alt.perf.custom.install.DF
imagetype=linux
osarch=ppc64le
osdistroname=rhels7.5-alternate-ppc64le
osname=Linux
osvers=rhels7.5-alternate
otherpkgdir=/install/REPO/software
otherpkglist=/install/xcat_clusters/osimage/rhels/common/otherpkglist/essl.otherpkglist,/install/xcat_clusters/osimage/rhels/common/otherpkglist/pessl.otherpkglist,/install/xcat_clusters/osimage/rhels/common/otherpkglist/xlc.otherpkglist,/install/xcat_clusters/osimage/rhels/common/otherpkglist/xlf.otherpkglist,/install/xcat_clusters/osimage/rhels/common/otherpkglist/PPT.otherpkglist,/install/xcat_clusters/osimage/rhels/common/oth …
```

Support list in YAML for user comments for osimage object

---

xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/shell.py

fix https://github.com/xcat2/xcat-inventory/issues/88
UT:
```
[root@briggs01 tmp]# xcat-inventory export -t site
schema_version: '1.0'
site:
clustersite:
SNsyncfiledir: /var/xcat/syncfiles
auditnosyslog: '0'
auditskipcmds: ALL
blademaxp: '64'
cleanupxcatpost: 'no'
consoleondemand: 'no'
databaseloc: /var/lib
db2installloc: /mntdb2
dhcpinterfaces: briggs01.pok.stglabs.ibm.com|enP34p1s0f0,,enP34p1s0f0.12,enP34p1s0f1:noboot
dhcplease: '300'
disjointdhcps: '0'
dnshandler: ddns
domain: pok.stglabs.ibm.com
enableASMI: 'no'
forwarders: 10.6.29.1
fsptimeout: '0'
hierarchicalattrs: postscripts
installdir: /install
ipmimaxp: '64'
ipmiretries: '3'
ipmitimeout: '2'
master: 172.12.253.27
maxssh: '8'
nameservers: 172.12.253.27
nodesyncfiledir: /var/xcat/node/syncfiles
ntpservers: <xcatmaster> …
```

changing the default format to yaml

---

xcat-inventory/xcclient/inventory/globalvars.py
xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/shell.py
xcat-inventory/xcclient/inventory/utils.py
xcat-inventory/xcclient/inventory/vutil.py

UT:
```
[root@briggs01 inventory]# time xcat-inventory export -tsite
schema_version: '1.0'
site:
clustersite:
SNsyncfiledir: /var/xcat/syncfiles
auditnosyslog: '0'
auditskipcmds: ALL
blademaxp: '64'
cleanupxcatpost: 'no'
consoleondemand: 'no'
databaseloc: /var/lib
db2installloc: /mntdb2
dhcpinterfaces: briggs01.pok.stglabs.ibm.com|enP34p1s0f0,,enP34p1s0f0.12,enP34p1s0f1:noboot
dhcplease: '300'
disjointdhcps: '0'
dnshandler: ddns
domain: pok.stglabs.ibm.com
enableASMI: 'no'
forwarders: 10.6.29.1
fsptimeout: '0'
hierarchicalattrs: postscripts
installdir: /install
ipmimaxp: '64'
ipmiretries: '3'
ipmitimeout: '2'
master: 172.12.253.27
maxssh: '8'
nameservers: 172.12.253.27
nodesyncfiledir: /var/xcat/node/syncfiles
ntpservers: <xcatmaster>
powerinterval: '0'
ppcmaxp: '64'
ppcretry: '3' …
```

performance enhance: avoid running `lsxcatd -v` time to time

---

xcat-inventory/xcclient/inventory/manager.py

UT:
```
[root@briggs01 inventory]# xcat-inventory export -tcredentia
Error: Invalid object type: "credentia". Valid types: "node,passwd,osimage,network,zone,credential,policy,route,site"
[root@briggs01 inventory]# echo $?
1
```

print valid type values when invalid type passed in

---

xcat-inventory/xcclient/inventory/globalvars.py
xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/schema/1.0/osimage.yaml
xcat-inventory/xcclient/inventory/shell.py
xcat-inventory/xcclient/inventory/utils.py
xcat-inventory/xcclient/inventory/vutil.py

* expose several implicit variables in inventory file to import;
* add subcommand 'envlist' to show the description and usage of the implicit variables
UT:
```
[root@briggs01 tmp]# xcat-inventory envlist
#<Notice> : refer the variables in the inventory file with format "{{variable name}}"#
variable name   : description
GITBRANCH       : the current git branch name of the inventory file to import
GITCOMMIT       : the current git commit number of the inventory file to import
OBJNAME         : the object name to import
GITTAG          : the current git tag of the inventory file to import
GITROOT         : the root path of the git repo where the inventory file resides in
```
```
[root@briggs01 osimage]# cat ./myosimage.rh7.compute.netboot
osimage:
myosimage.rh7.compute.netboot: …
```

implicit variable support

---

xcat-inventory/xcclient/inventory/schema/0.1/node.yaml
xcat-inventory/xcclient/inventory/schema/0.2/node.yaml

fix issue :https://github.com/xcat2/xcat-inventory/issues/113:
* remove the validation criteria for `network_info.primarynic.switchport `
* add "2c" to the legacy values for `security_info.snmp.version `
UT: 
```
mporting object: mgmtImporting object: publicImporting object: systemImporting object: ipmiImporting object: omapiImporting object: openbmcImporting object: alpinetdsImporting object: extgwyImporting object: 4.5Importing object: 4.4Importing object: 4.7Importing object: 4.6Importing object: 1.2Importing object: 4.9Importing object: 4.8Importing object: 1Importing object: 3Importing object: 2Importing object: 4Importing object: 2.3Importing object: 2.1Inventory import successfully!
--
```

refine node schema validation criteria

---

README.md
xcat-inventory/xcclient/inventory/exceptions.py
xcat-inventory/xcclient/inventory/inventorydiff.py
xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/shell.py
xcat-inventory/xcclient/inventory/structurediff.py
xcat-inventory/xcclient/inventory/utils.py

#106 
* CLI -- return a dict with diff
```
diff_dict = StructureDiff().diff(d1, d2, self.isall)
```
diff_dict like this:
```
{'node': {'c910f03c17': {'engines': {'hardware_mgt_engine': {'engine_info': {'-diff': {'bmc': '50.3.17.1'}}}}}}, '-diff': {'schema_version': 'latest'}, '+diff': {'schema_version': '1.0'}}
```
* UT:
```
usage: xcat-inventory diff [--files FILE FILE] [--filename FILENAME]
[--source FILE] [--all]
Diff files or file vs xCAT DB
Arguments:
--files FILE FILE    compare the given 2 inventory files
--filename FILENAME  the filename want to show, be used with "--files"
--source FILE        compare the given inventory file with xCAT DB
--all                compare the given inventory file with the whole xCAT
DB, be used with "--source". If not specified, will
only compare the …
```

support diff file with xcat db object

---

makepythonrpm
xcat-inventory/xcclient/inventory/dbfactory.py
xcat-inventory/xcclient/inventory/globalvars.py
xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/utils.py
xcat-inventory/xcclient/shell.py

* add more verbose info
* use "CLOADER" to accelerate yaml.load
fix #117 :
UT:
```
[root@c910f03c05k21 inventory]# xcat-inventory   import -f /tmp/cluster -t policy -v
start to import "policy" type objects
preprocessing "policy" type objects
converting object "1.2" to table entries
converting object "7.2" to table entries
converting object "7.3" to table entries
converting object "7.1" to table entries
converting object "7.6" to table entries
converting object "7.4" to table entries
converting object "2.3" to table entries
converting object "2.1" to table entries
converting object "4.5" to table entries
converting object "4.4" to table entries
converting object "4.7" to table entries
converting object "4.6" to table entries
converting object "4.9" to table entries
converting object "4.8" …
```

fix add more verbose information during xcat-inventory import #117

---

xcat-inventory/xcclient/inventory/dbfactory.py
xcat-inventory/xcclient/inventory/manager.py

fix https://github.com/xcat2/xcat-inventory/issues/122:
redirect `import` progress message from STDERR to STDOUT
UT:
```
[root@briggs01 ~]# xcat-inventory import -f /tmp/policy 2>/dev/null
loading inventory date in "/tmp/policy"
start to import "policy" type objects
preprocessing "policy" type objects
writting "policy" type objects
[root@briggs01 ~]# xcat-inventory import -f /tmp/policy -v 2>/dev/null
loading inventory date in "/tmp/policy"
start to import "policy" type objects
preprocessing "policy" type objects
converting object "1.2" to table entries
converting object "1.3" to table entries
converting object "7.1" to table entries
converting object "2.3" to table entries
converting object "2.1" to table entries
converting object "4.5" to table entries …
```

fix issue Changes to latest commits cause reduction in stdout messages that were useful. #122

---

xcat-inventory/xcclient/inventory/inventorydiff.py
xcat-inventory/xcclient/inventory/structurediff.py

1. Support ``type_changes`` diff type from deepdiff.
2. If one or more file is empty, use ``diff`` cmd to compare.
UT:
```
{
"site": {
"clustersite": {
-            "ipmimaxp": "64"
+            "ipmimaxp": ""
}
}
}
====================BEGIN=====================
--- mytest.json
+++ mytest.json
@@ -0,0 +1,4 @@
+hpc/ESSL/essl-6.1.0-0/repo/ppc64le/essl.3264.rte hpc/ESSL/essl-6.1.0-0/repo/ppc64le/essl.3264.rtecuda
+hpc/ESSL/essl-6.1.0-0/repo/ppc64le/essl.6464.rte hpc/ESSL/essl-6.1.0-0/repo/ppc64le/essl.common
+hpc/ESSL/essl-6.1.0-0/repo/ppc64le/essl.license hpc/ESSL/essl-6.1.0-0/repo/ppc64le/essl.man
+hpc/ESSL/essl-6.1.0-0/repo/ppc64le/essl.msg hpc/ESSL/essl-6.1.0-0/repo/ppc64le/essl.rte
====================END=====================
```

support type_changes modification

---

xcat-inventory/xcclient/shell.py

#129 
In pull request #118, modified to pass ``args`` to ``subcommand_parser.parse_args`` not ``argv``(include all options). So if ``'-h' or '--help'`` in argv, append to args.
UT:
```
usage: xcat-inventory export [-t <type>] [-x EXCLUDE] [-o <name>] [-f <path>]
[-d <directory>] [-s <version>]
[--format <format>]
Export the inventory data from xcat database
Arguments:
-t <type>, --type <type>
comma "," delimited types of objects to export, valid
values: node,passwd,osimage,network,zone,credential,po
licy,route,site. If not specified, all objects in xcat
databse will be exported
-x EXCLUDE, --exclude EXCLUDE
types to be excluded when exporting all, delimited
with Comma(,).
-o <name>, --objects <name>
names of the objects to export, delimited with
Comma(,). If not specified, all objects of …
```

fix issue 129, print out help msg when run xcat-inventory export -h

---

build-ubuntu

fix xcat-inventory --version print #VERSION_SUBSTITUTE# for https://github.com/xcat2/xcat-inventory/issues/133
UT:
```
###################################
###################################
###################################
###################################
VERINFO 0.1.5 (git commit 7ae3b70d6f4039f83870766d94d9ee574b58ce76)
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package xcat-inventory
dpkg-buildpackage: source version 0.1.5-c21
dpkg-buildpackage: source distribution UNRELEASED
... ...
dpkg-deb: building package 'xcat-inventory' in '../xcat-inventory_0.1.5-c21_all.deb'.
pwd
/root/baiyuan/xcat-inventory/xcat-inventory
dpkg-genchanges  >../xcat-inventory_0.1.5-c21_ppc64el.changes
dpkg-genchanges: warning: the current version …
```

fix xcat-inventory --version print #VERSION_SUBSTITUTE#

---

xcat-inventory/xcclient/inventory/dbsession.py

for https://github.com/xcat2/xcat-inventory/issues/143
Description:
make python understand 'utf8mb4' as an alias for 'utf8'
UT:
```
[root@c910f04x12v02 inventory]# xcat-inventory -V
0.1.5 (git commit 6301c1213c88cdfb2221cfe34af4d0ee1d83129a)
```

fix unknown encoding utf8mb4

---

xcat-inventory/xcclient/inventory/dbobject.py
xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/schema/2.0/node.yaml
xcat-inventory/xcclient/inventory/schema/2.0/prodkey.yaml
xcat-inventory/xcclient/inventory/xcatobj.py

fix https://github.com/xcat2/xcat-inventory/issues/152
currently, the `prodkey` is a table with multiple primary keys, refine the schema of node object to include     `security_info:productkey` as a subject of  `prodkey`
UT:
```
[root@c910f03c01p13 inventory]# tabdump prodkey
#node,product,key,comments,disable
"bogusnode","os","productkey",,
"bogusnode","product1","productkey",,
[root@c910f03c01p13 inventory]# xcat-inventory export -t node -o bogusnode
node:
bogusnode:
deprecated:
cfgmgtcfgmgr: cfgmgr
cfgmgtcfgserver: cfgserver
cfgmgtroles: cfgmgtroles
chainondiscover: ondiscover
hypervisorcluster: hostcluster
hypervisorinterface: hostinterface
hypervisormgr: hostmanager
hypervisortype: hosttype
iscsipasswd: iscsipassword
iscsiserver: iscsiserver
iscsitarget: iscsitarget
iscsiuserid: …
```

support prodkey as a subobject for node

---

makepythonrpm

fix issue https://github.com/xcat2/xcat-inventory/issues/154:
```
[root@c910f03c05k21 xCAT-Incubator]# rm -rf /root/rpmbuild/SOURCES/
[root@c910f03c05k21 xCAT-Incubator]# bash -x ./makepythonrpm xcat-inventory
+ '[' -z xcat-inventory ']'
++ git describe --long --tags
++ cut -d- -f 1
++ tail -c +2
+ VERSION=0.1.5
++ git describe --long --tags
++ cut -d- -f 2
+ NUMCOMMITS=39
+ '[' 39 '!=' 0.1.5 ']'
+ VERSION=0.1.5
+ echo 0.1.5
++ uname
+ OSNAME=Linux
++ git rev-parse HEAD
+ GITCOMMIT=17933160163c1983f222d877d955d721087c5ea3
+ RPMROOT=/root/rpmbuild
+ rpmbuild --version
+ '[' 0 -gt 0 ']'
+ '[' xcat-inventory = xcat-inventory ']'
+ makepythoncli xcat-inventory
+ RPMNAME=xcat-inventory
+ SPEC_FILE=xcat-inventory.spec
+ VERINFO='0.1.5 (git commit 17933160163c1983f222d877d955d721087c5ea3)'
+ …
```

fix rpm  build issue

---

xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/vutil.py

fix issue https://github.com/xcat2/xcat-inventory/issues/153:
* support the old inventory format with ',' delimited string of list
* capture error during file copying
UT:
```
[root@c910f03c01p13 test_myimage]# xcat-inventory import -d /opt/xcat/share/xcat/tools/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage
loading inventory date in "/opt/xcat/share/xcat/tools/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage/definition.json"
start to import "osimage" type objects
preprocessing "osimage" type objects
writting "osimage" type objects
Warning: the / already exists, will be overwritten
Error encountered while copying "/opt/xcat/share/xcat/tools/autotest/testcase/xcat-inventory/templates/cluster_invdir/o …
```

fix issue "[FVT]:xcat-inventory import could not find the correct files/dir #153"

---

build.sh

build script for xcat-inventory build on docker
Call ``makepythonrpm xcat-inventory`` or ``./build-ubuntu -c`` on OS.

build script for xcat-inventory build on docker

---

xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/shell.py

#149 
UT:
```
usage: xcat-inventory import [-t <type>] [-o <name>] [-f <path>]
[-d <directory>] [-s <version>] [--dry] [-c]
[-e <env_var>] [--env-file <env_file>]
Import inventory file to xcat database
Arguments:
-t <type>, --type <type>
comma "," delimited types of the objects to import,
valid values: node,credential,passwd,prodkey,site,netw
orkconn,network,zone,route,osimage,policy. If not
specified, all objects in the inventory file will be
imported
-o <name>, --objects <name>
names of the objects to import, delimited with
Comma(,). If not specified, all objects of the
specified type in the inventory file will be imported
-f <path>, --path <path>
path of the inventory file to import
-d <directory>, --dir <directory>
path of the inventory directory
-s <version>, --schema-version …
```

support --env-file option to import env variables

---

xcat-inventory/xcclient/inventory/manager.py

fix issue #175 
UT:
```
[root@c910f03c05k21 inventory]# xcat-inventory export -t node
node:
node1:
device_type: server
network_info:
connections:
- interface: eth1
switch: sw1
switchport: '1'
vlan: '1'
- interface: eth2
switch: sw1
switchport: '2'
vlan: '2'
obj_info:
groups: all
obj_type: node
role: compute
node2:
device_type: server
network_info:
connections:
- interface: eth1
switch: sw2
switchport: '1'
vlan: '1'
- interface: eth2
switch: sw2
switchport: '2'
vlan: '2'
obj_info:
groups: all
obj_type: node
role: compute
xcatdefaults:
device_type: server
engines:
netboot_engine:
engine_info:
postbootscripts: otherpkgs
postscripts: syslog,remoteshell,syncfiles
obj_type: group
role: compute
schema_version: '2.0'
#Version 2.14.5 (git commit 5bab3f8bac3374cd9cb2e26b4a71c7cb32bb1126, built Mon …
```

fix issue `import -c` does not work properly on `network_info.connections` and `security_info.productkey` attributes of node #175

---

README.md

Just update the document to add more information about `XCAT_VERNO` and `XCAT_SERVER` when running in container.

update the README to add XCAT_VERNO and XCAT_SERVER variable for running in container

---

README.md
xcat-inventory/xcclient/allien/app.py
xcat-inventory/xcclient/allien/invmanager.py
xcat-inventory/xcclient/allien/resources/site.py
xcat-inventory/xcclient/xcatd/client/xcat_ssl.py

Implement the Site restful APIs (https://github.ibm.com/xcat2/task_management/issues/140):
- `/globalconf/sites`  GET (no need for POST as now only one default context)
- `/globalconf/sites/<context>`  GET/PUT/PATCH (For GET, supporting query parameters of attributes)
- `/globalconf/sites/<context>/<attr>` GET/POST/DELETE
Implement a general delete method `del_inventory_by_type` in `invmanager.py`, it will call xcatd client to do a `rmdef` action.
Waiting full UT.

Implement Site restful APIs

---

xcat-inventory/xcclient/inventory/backend.py
xcat-inventory/xcclient/inventory/dbfactory.py
xcat-inventory/xcclient/inventory/dbobject.py
xcat-inventory/xcclient/inventory/dbsession.py
xcat-inventory/xcclient/inventory/globalvars.py
xcat-inventory/xcclient/inventory/inventorydiff.py
xcat-inventory/xcclient/inventory/manager.py
xcat-inventory/xcclient/inventory/shell.py
xcat-inventory/xcclient/inventory/structurediff.py
xcat-inventory/xcclient/inventory/utils.py
xcat-inventory/xcclient/inventory/vutil.py
xcat-inventory/xcclient/inventory/xcatobj.py
xcat-inventory/xcclient/shell.py

Trigger CI on master branch, and CI could ensure python2 is working.
UT it on a python3 environtment:
```
python --version
Python 3.5.2
And need to workaround /opt/xcat/share/xcat/tools/autotest/testcase/xcat_inventory/validatehelper to use /usr/bin/python2
sudo bash -c '. /etc/profile.d/xcat.sh &&  xcattest -f /root/xcat.conf -s inventory_ci > /tmp/mylog1'
grep END /tmp/mylog1|grep Failed
------END::xcat_inventory_diff_files_filename::Failed::Time:Wed May  8 05:56:36 2019 ::Duration::1 sec------
------END::backend::Failed::Time:Wed May  8 06:17:57 2019 ::Duration::360 sec------
------END::xcat_inventory_diff_source::Failed::Time:Wed May  8 06:20:11 2019 ::Duration::10 sec------
------END::xcat_inventory_diff_files::Failed::Time:Wed May  8 06:27:01 2019 ::Duration::1 sec------
```
The …

python3 supporting

---

xcat-inventory/xcclient/allien/resources/__init__.py
xcat-inventory/xcclient/allien/resources/network.py
xcat-inventory/xcclient/allien/resources/node.py
xcat-inventory/xcclient/allien/resources/osimage.py
xcat-inventory/xcclient/allien/resources/service.py
xcat-inventory/xcclient/allien/srvmanager.py
xcat-inventory/xcclient/xcatd/client/xcat_cmd_helpers.py
xcat-inventory/xcclient/xcatd/xcat_client.py

This PR is for https://github.ibm.com/xcat2/task_management/issues/136, and below changes included:
- `rinstall` python client to xcatd for `rinstall`
- `mkconsole` python client to xcatd for `makegocons`
- single node provision API with POST `/system/nodes/{node}/_operation`
- multiple nodes provision API with POST `/manager/provision`

rinstall RESTful API

---

xcat-inventory/xcclient/allien/invmanager.py
xcat-inventory/xcclient/allien/resources/security.py
xcat-inventory/xcclient/inventory/dbfactory.py
xcat-inventory/xcclient/inventory/manager.py

For
https://github.ibm.com/xcat2/task_management/issues/145
Description:
1. add updating and adding xCAT table entry in xcat-inventory
2. add secrets post API
UT:
1. 
/inventory/secrets | POST | create a new secret object |  
-- | -- | -- | --
```
curl -X POST "http://10.4.41.7:5000/api/v2/security/secrets" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{    \"kind\": \"test\",    \"spec\": {      \"username\": \"xc\",      \"password\": \"cluster\"    }}"
{
"message": "new user is created.",
"id": "test_xc"
}
```
2. 
/inventory/secrets/{id} | POST | modify a specified type of secrets object |  
-- | -- | -- | --
```
curl -X POST "http://10.4.41.7:5000/api/v2/security/secrets/test_xcx" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{ …
```

add secrets api and inventary table update

---

xcat-inventory/xcclient/allien/invmanager.py
xcat-inventory/xcclient/inventory/dbfactory.py

For https://github.ibm.com/xcat2/task_management/issues/263
PATH | METHOD | Description | Parameters
-- | -- | -- | --
/inventory/node/<nodename>/_detail | GET | get a node object defined in store |  
UT:
```
[root@byrh07 ~]# time curl -X GET "http://10.4.41.7:5000/api/v2/system/nodes/login4/_detail" -H  "accept: application/json"
{
"meta": {
"name": "login4"
},
"spec": {
"obj_type": "node",
"engines": {
"netboot_engine": {
"engine_info": {
"postbootscripts": "otherpkgs,",
"chain": "runcmd=bmcsetup,osimage=compute",
"osimage": "login",
"postscripts": "syslog,remoteshell,syncfiles,confignetwork -s,setroute,nvidia-exclusive-mode,puppet_agent,gpfsclient,enablekdump"
},
"engine_type": "petitboot"
},
"hardware_mgt_engine": {
"engine_type": "openbmc"
},
"console_engine": {
"engine_type": …
```

default node details API implementation when site.hierarchicalattrs is empty

---

xcat-inventory/xcclient/allien/invmanager.py
xcat-inventory/xcclient/allien/resources/node.py
xcat-inventory/xcclient/allien/srvmanager.py

https://github.ibm.com/xcat2/task_management/issues/188
1, replace with the new get_nodes_list method;
2, add path for node status
```
curl http://10.6.27.1:5000/api/v2/system/nodes/mid05tor12cn03/_status
{
"status": {
"boot": {
"state": "powering-on",
"updated_at": "05-14-2019 01:59:19"
},
"sync": {
"state": "synced",
"updated_at": "02-13-2019 00:26:52"
}
},
"meta": {
"name": "mid05tor12cn03"
}
}
```

Status API for specific node

---

xcat-inventory/xcclient/allien/srvmanager.py

Terraform provider need to run makedns first before provision the node, to simply their logic, to add it in api side.

Makedns before rinstall

---

xcat-inventory/xcclient/allien/resources/__init__.py

To disable url authorization checking when debugging:
Run the application like this: 
FLASK_DEBUG=1 XCAT_VERNO=2.14.6 XCAT_SERVER=10.6.27.1 DISABLE_AUTH_FOR_DEBUG=yes python main.py
The `DISABLE_AUTH_FOR_DEBUG` option take affect only in Flask debug mode.

add env variable DISABLE_AUTH_FOR_DEBUG to disable url authorization

---

xcat-inventory/xcclient/allien/authmanager.py
xcat-inventory/xcclient/allien/resources/auth.py

The expire time is updated as now+24hours
```
[root@briggs01 ~]# docker exec -it ac0717b7d2bd /bin/bash
[root@ac0717b7d2bd xcat-apiserver]# date
Wed May 22 02:50:55 UTC 2019
[root@briggs01 ~]# curl -X POST -H "Content-Type: application/json" -d '{"username":"zet809", "password":"passw0rd"}' http://127.0.0.1:5001/api/v2/auth/login
{
"token": {
"expire": "2019-05-23 02:51:00",
"id": "6e5b7716-7c3c-11e9-b63f-0242ac110002"
}
}
```

Update expire time as now+24hours

---

xcat-inventory/xcclient/allien/invmanager.py
xcat-inventory/xcclient/allien/resources/auth.py
xcat-inventory/xcclient/allien/resources/inventory.py
xcat-inventory/xcclient/allien/resources/network.py
xcat-inventory/xcclient/allien/resources/node.py
xcat-inventory/xcclient/allien/resources/nodehm.py
xcat-inventory/xcclient/allien/resources/osimage.py
xcat-inventory/xcclient/allien/resources/security.py
xcat-inventory/xcclient/allien/resources/site.py

UT as below, just use one as an example:
```
curl -X GET "http://10.6.27.1:5000/api/v2/globalconf/sites" -H  "accept: application/json" -H  "Authorization: token c997632c-7dfb-11e9-a021-0cc47aea9e02"
[
{
"meta": {
"name": "clustersite"
},
"spec": {
"vsftp": "n",
"ipmitimeout": "2",
"consoleondemand": "no",
"enableASMI": "no",
"ipmimaxp": "64",
"xcatdebugmode": "1",
"ipmiretries": "3",
"forwarders": "10.0.0.101",
"blademaxp": "64",
"db2installloc": "/mntdb2",
"domain": "pok.stglabs.ibm.com",
"auditskipcmds": "ALL",
"nameservers": "10.6.27.1",
"SNsyncfiledir": "/var/xcat/syncfiles",
"xcatiport": "3002",
"syspowerinterval": "0",
"ppcmaxp": "64",
"xcatconfdir": "/etc/xcat",
"installdir": "/install",
"xcatdport": "3001",
"powerinterval": "0",
"master": "10.6.27.1",
"auditnosyslog": "0", …
```

Put all APIs using authentication for Security

---

travis.pl

Lately, like for #225, when Travis regression runs, the `hostname -i` returns 2 entries, and that sets `xcattest` variable `DSTMN` to be:
```
'DSTMN=127.0.0.1 127.0.1.1',
```
As a result, testcases can not deal with such setting and fail.
This PR makes sure only first entry is used for setting `DSTMN`

Make sure single ip for management node

---

travis.pl
xcat-inventory/xcclient/inventory/backend.py

This PR:
* Adds small print enhancements to Travis testcase run.
* Fixed errors in `backend.py` of ` configparser` usage. Data has to be converted to dictionary before reference. It appears to have worked with older versions of Python, but now, it seems, newer version of Python is used when Travis VM is created. As a result the following testcase run errors are displayed:
```
'RUN:xcat-inventory init [Tue Aug 18 16:57:40 2020]',
'ElapsedTime:1 sec',
'RETURN rc = 1',
'OUTPUT:',
'Traceback (most recent call last):',
'  File "/opt/xcat/lib/python/xcclient/inventory/shell.py", line 167, in main',
'    InventoryShell(\'xcat-inventory\',\'0.1.7 (git commit 196b9ca447c77510e95c88ae544f7be146cebe46)\').run(sys.argv[1:], \'1.0\', "xCAT inventory management tool")',
'  File …
```

Travis output improvements
