- xcat-inventory/xcclient/inventory/schema/1.0/node.yaml
the arch `armv71` should be `armv7l`
> correct the arch validation criteria

- xcat-inventory/xcclient/inventory/manager.py
UT:
```
[root@c910f03c05k21 xCAT-Incubator]# xcat-inventory import -t node -o aasdsadasd -f /tmp/cluster
Error: cannot find node objects: aasdsadasd!
```
> refine message according to test case

- xcat-inventory/xcclient/inventory/manager.py
fix issue #50 
UT:
```
[root@c910f03c05k21 inventory]# lsdef -t osimage
c7livecd  (osimage)
compute  (osimage)
cumulus-3.1.0-armel  (osimage)
cumulus3.4.1-amd64  (osimage)
cumulus3.5.2-armel  (osimage)
imagebase  (osimage)
ist.perf.custom.netboot.DL  (osimage)
ist.redhat-alt.perf.custom.netboot.DL  (osimage)
ist.redhat.perf.custom.netboot.DL  (osimage)
rhels6.4-ppc64le-install-compute  (osimage)
rhels6.5-x86_64-install-compute  (osimage)
rhels6.5-x86_64-install-service  (osimage)
rhels6.5-x86_64-netboot-compute  (osimage)
rhels6.5-x86_64-statelite-compute  (osimage)
rhels7.3-ppc64le-install-compute  (osimage)
rhels7.3-ppc64le-install-service  (osimage)
rhels7.3-ppc64le-netboot-compute  (osimage)
rhels7.3-ppc64le-stateful-mgmtnode  (osimage)
rhels7.3-ppc64le-statelite-compute  (osimage) …
```
> fix issue `xcat-inventory import -d <> -c` can only see the last one after imported #50

- xcat-inventory/xcclient/inventory/exceptions.py
- xcat-inventory/xcclient/inventory/manager.py
- xcat-inventory/xcclient/inventory/shell.py
- xcat-inventory/xcclient/inventory/xcatobj.py
for https://github.com/xcat2/xcat-inventory/issues/51:
UT:
```
[root@c910f03c05k21 xCAT-Incubator]# SWDIR=/install/REPO/ GITREPO=/install/xcat_cluster xcat-inventory import -f /tmp/oo
Importing object: aa
Importing object: xcatdefault
Importing object: ipmi
Importing object: switch
Importing object: zzzz
Importing object: omapi
Importing object: system
Importing object: 4.5
Importing object: 4.4
Importing object: 4.7
Importing object: 4.6
Importing object: 1.2
Importing object: 7.2
Importing object: 4.9
Importing object: 4.8
Importing object: 1
Importing object: 7.3
Importing object: 3
Importing object: 7.1
Importing object: 7.6
Importing object: 4
Importing object: 7.4
Importing object: 2.3
Importing object: 2
Importing object: 2.1
Error: failed to validate attribute …
```
> enhance the validation code to show all the validation result in one time for import

- xcat-inventory/xcclient/inventory/schema/1.0/node.yaml
- xcat-inventory/xcclient/inventory/schema/1.0/osimage.yaml
refine the schema to put V{} in the expression body to param list
> refine the schema to move V{} in the expression body to param list

- xcat-inventory/xcclient/inventory/manager.py
change this according to request from @whowutwut  , change the length of {{GITCOMMIT}} to 7 to differentiate with {{GITTAG}}
> change the length of {{GITCOMMIT}} to 7

- xcat-inventory/xcclient/inventory/inventorydiff.py
- xcat-inventory/xcclient/inventory/structurediff.py
#121
1. print nothing when no difference
2. --filename is list type, get first element as filename.
> fix issue 121, print nothing when no difference

- xcat-inventory/debian/control
- xcat-inventory/debian/dirs
- xcat-inventory/debian/install
- xcat-inventory/requirements.txt
- xcat-inventory/xcat-inventory.spec
- xcat-inventory/xcclient/inventory/backend.py
- xcat-inventory/xcclient/inventory/exceptions.py
- xcat-inventory/xcclient/inventory/inventory.cfg
- xcat-inventory/xcclient/inventory/inventorydiff.py
- xcat-inventory/xcclient/inventory/manager.py
- xcat-inventory/xcclient/inventory/schema/0.1/credential.yaml
- xcat-inventory/xcclient/inventory/schema/1.0/osimage.yaml
- xcat-inventory/xcclient/inventory/shell.py
- xcat-inventory/xcclient/inventory/utils.py
- xcat-inventory/xcclient/inventory/vutil.py
- xcat-inventory/xcclient/inventory/xcatobj.py
- xcat-inventory/xcclient/shell.py
based on https://github.com/xcat2/xcat-inventory/issues/90
newly added backend subcommands:
```
[root@c910f03c05k21 inventory]# xcat-inventory -h
usage: xcat-inventory [-h] [--debug] [-v] [-V] <subcommand> ...
xCAT inventory management tool
Positional arguments:
<subcommand>
checkout          checkout to a specified revision
commit            create a revision and push to remote backend
diff              show inventory diff between files or file vs xCAT DB
envlist           Show implicit environment variables during 'xcat-
inventory import', which can be used in inventory files
with format '{{<environment variable name>}}'
export            Export the inventory data from xcat database
help              Display help about this program or one of its
subcommands.
import            Import …
```
> prototype of git backend support 

- xcat-inventory/xcclient/inventory/backend.py
- xcat-inventory/xcclient/inventory/manager.py
- xcat-inventory/xcclient/inventory/schema/0.1/credential.yaml
- xcat-inventory/xcclient/inventory/shell.py
This PR includes:
* add "-x|--exclude" for import
* exclude `credential` in `checkout`, `diff`,`commit`
> add "-x|--exclude" for import

- xcat-inventory/xcclient/inventory/manager.py
- xcat-inventory/xcclient/inventory/utils.py
this PR is to fix issue #181 
UT:
```
[root@c910f03c05k21 inventory]# xcat-inventory import -d /tmp/backend_test/git/repo/ -c
Error: cannot find any xCAT inventory object in directory "/tmp/backend_test/git/repo/"
Error: cannot find any xCAT inventory object in directory "/tmp/backend_test/git/repo/"
You have new mail in /var/spool/mail/root
[root@c910f03c05k21 inventory]#
```
> fix issue `import -d <dir> -c` will panic if <dir> is blank #181

- xcat-inventory/xcclient/inventory/dbobject.py
- xcat-inventory/xcclient/inventory/manager.py
- xcat-inventory/xcclient/inventory/schema/2.0/osdistro.yaml
- xcat-inventory/xcclient/inventory/xcatobj.py
this PR is to fix issue https://github.com/xcat2/xcat-inventory/issues/184:
UT result:
```
[root@briggs01 ~]# tabdump osdistro
#osdistroname,basename,majorversion,minorversion,arch,type,dirpaths,comments,disable
"rhels7.4-snap2-ppc64le","rhels","7","4","ppc64le","Linux","/install/rhels7.4-snap2/ppc64le",,
"rhels7.4-snap1-ppc64le","rhels","7","4","ppc64le","Linux","/install/rhels7.4-snap1/ppc64le",,
"rhels7.4-snap6-ppc64le","rhels","7","4","ppc64le","Linux","/install/rhels7.4-snap6/ppc64le",,
"ubuntu17.10-ppc64el","ubuntu","17","10","ppc64el","Linux","/install/ubuntu17.10/ppc64el",,
"rhels7.4-alternate-ppc64le","rhels","7","4","ppc64le","Linux","/install/rhels7.4-alternate/ppc64le",,
"rhels7.4-rc1-ppc64le","rhels","7","4","ppc64le","Linux","/install/rhels7.4-rc1/ppc64le",, …
```
> support osdistro object

- xcat-inventory/xcclient/allien/invmanager.py
- xcat-inventory/xcclient/allien/resources/osimage.py
Implement Osimage restful APIs for: https://github.ibm.com/xcat2/task_management/issues/142
Changes summaries:
1. Implement a general validate method `validate_resource_input_data` in `invmanager.py`.
2. Osimage restful APIs includes:
1. `inventory/osimages`  POST/GET
2. `inventory/osimages/{name}` GET/PUT/DELETE/PATCH
UT results:
1. `inventory/osimages/{name}` DELETE OK
```
]# lsdef -t osimage
rhels7.6  (osimage)
rhels7.6-test  (osimage)
]# curl -X DELETE "http://10.4.41.7:5000/api/v2/inventory/osimages/rhels7.6" -H  "accept: application/json"
null
]# lsdef -t osimage
rhels7.6-test  (osimage)
```
2. `inventory/osimages/{name}` DELETE Not Found
```
]# curl -X DELETE "http://10.4.41.7:5000/api/v2/inventory/osimages/rh" -H  "accept: application/json"
{
"message": "Could not find an object …
```
> Implement Osimage restful APIs

- xcat-inventory/xcclient/allien/resources/osimage.py
- xcat-inventory/xcclient/xcatd/client/xcat_cmd_helpers.py
- xcat-inventory/xcclient/xcatd/xcat_client.py
For https://github.ibm.com/xcat2/task_management/issues/143
Description:
Add distros DB API delete, get, post 
UT:
1.  get distro list defined in store
```
curl -X GET "http://10.4.41.7:5000/api/v2/inventory/distros" -H  "accept: application/json"
[
{
"meta": {
"name": "rhels7.6-x86_64"
},
"spec": {
"majorversion": "7",
"minorversion": "6",
"arch": "x86_64",
"basename": "rhels",
"dirpaths": "/install/rhels7.6/x86_64",
"type": "Linux"
}
}
]
```
2. get specified distro:
```
curl -X GET "http://10.4.41.7:5000/api/v2/inventory/distros/rhels7.6-x86_64" -H  "accept: application/json"
{
"meta": {
"name": "rhels7.6-x86_64"
},
"spec": {
"majorversion": "7",
"minorversion": "6",
"arch": "x86_64",
"basename": "rhels",
"dirpaths": "/install/rhels7.6/x86_64",
"type": "Linux"
}
}
```
3. delete method: …
> add distros DB API

- xcat-inventory/xcclient/allien/invmanager.py
- xcat-inventory/xcclient/allien/resources/inventory.py
Implement the requirements in https://github.ibm.com/xcat2/task_management/issues/139
to import/export the raw inventory json data by types.
> Inventory import/export api

- .gitignore
- xcat-inventory/xcclient/allien/resources/inventory.py
- xcat-inventory/xcclient/allien/resources/security.py
complement the API described in https://github.ibm.com/xcat2/task_management/issues/144
> Implement Policy api

- xcat-inventory/xcclient/allien/resources/network.py
This for https://github.ibm.com/xcat2/task_management/issues/141
Route Resource
1) Get all the routes defined in the route table
````
]# curl -X GET "http://10.6.31.1:5000/api/v2/inventory/routes" -H  "accept: application/json"
[
{
"meta": {
"name": "20net"
},
"spec": {
"mask": "255.0.0.0",
"gateway": "0.0.0.0",
"ifname": "eth1",
"net": "20.0.0.0"
}
},
{
"meta": {
"name": "21net"
},
"spec": {
"mask": "255.255.0.0",
"gateway": "1.0.0.0",
"ifname": "eth3",
"net": "21.0.0.0"
}
}
]
````
2) delete 21net from route table
````
null
#routename,net,mask,gateway,ifname,comments,disable
"20net","20.0.0.0","255.0.0.0","0.0.0.0","eth1",,
````
3) POST 21net to route table
````
]# tabdump routes
#routename,net,mask,gateway,ifname,comments,disable
"20net","20.0.0.0","255.0.0.0","0.0.0.0","eth1",, …
```
> Add network/route API

- xcat-inventory/xcclient/allien/invmanager.py
- xcat-inventory/xcclient/allien/resources/security.py
- xcat-inventory/xcclient/inventory/dbfactory.py
- xcat-inventory/xcclient/inventory/manager.py
For task https://github.ibm.com/xcat2/task_management/issues/145
Description:
add secrets api get and delete method
UT:
1.
/inventory/secrets | GET | get secrets list defined in store
-- | -- | --
```
~]# curl -X GET "http://10.4.41.7:5000/api/v2/security/secrets" -H  "accept: application/json"
[
{
"kind": "xcat",
"spec": {
"username": "xxxx",
"password": "cluster"
},
"id": "xcat_xxxx"
},
{
"kind": "xcat",
"spec": {
"password": "cluster"
},
"id": "xcat"
},
{
"kind": "xcat",
"spec": {
"username": "root",
"password": "cluster"
},
"id": "xcat_root"
},
{
"kind": "test",
"spec": {
"username": "xxx",
"password": "cluster"
},
"id": "test_xxx"
},
{
"kind": "omapi",
"spec": {
"username": "xcat_key",
"password": "TlU1QmhxV3A5RlFVNDFQRm5iUzk5MlV4VWMwUFZ5UU8="
},
"id": "omapi_xcat_key"
},
{
"kind": …
```
> add secrets api get and delete method

- README.md
- xcat-inventory/xcclient/inventory/backend.py
- xcat-inventory/xcclient/inventory/dbfactory.py
- xcat-inventory/xcclient/inventory/dbobject.py
- xcat-inventory/xcclient/inventory/dbsession.py
- xcat-inventory/xcclient/inventory/globalvars.py
- xcat-inventory/xcclient/inventory/inventorydiff.py
- xcat-inventory/xcclient/inventory/manager.py
- xcat-inventory/xcclient/inventory/shell.py
- xcat-inventory/xcclient/inventory/structurediff.py
- xcat-inventory/xcclient/inventory/utils.py
- xcat-inventory/xcclient/inventory/vutil.py
- xcat-inventory/xcclient/inventory/xcatobj.py
- xcat-inventory/xcclient/shell.py
This is a back merge from master for python3 supporting (https://github.com/xcat2/xcat-inventory/pull/195)
Trigger it for a CI verification.
> Python3 merge from master

- xcat-inventory/xcclient/allien/invmanager.py
- xcat-inventory/xcclient/allien/resources/node.py
- xcat-inventory/xcclient/inventory/dbfactory.py
This is for https://github.ibm.com/xcat2/task_management/issues/146
- A method to fetch specified columns from table in dbfactory
- the API to leverage the method to return the all node name lists
Not required filters here as it is planned the `noderange` API for it later.
> Node list API

- xcat-inventory/requirements.txt
- xcat-inventory/xcclient/allien/app.py
- xcat-inventory/xcclient/allien/invmanager.py
- xcat-inventory/xcclient/allien/resources/__init__.py
- xcat-inventory/xcclient/allien/resources/auth.py
- xcat-inventory/xcclient/allien/resources/node.py
- xcat-inventory/xcclient/inventory/dbfactory.py
- xcat-inventory/xcclient/inventory/dbobject.py
For task: https://github.ibm.com/xcat2/task_management/issues/135
A draft to do login, auth refresh
* To login:
```
[root@briggs01 allien]# curl -X POST -H "Content-Type: application/json" -d '{"username":"zet809", "password":"xxx"}' http://127.0.0.1:5001/api/v2/auth/login
{
"token": {
"expire": "2019-05-15 07:22:21",
"id": "2e07c7a0-76e2-11e9-874a-0242ac110002"
}
}
```
* To use the token:
```
[root@briggs01 allien]# curl -X GET -H "Authorization: token 2e07c7a0-76e2-11e9-874a-0242ac110002" http://127.0.0.1:5001/api/v2/auth/refresh
Token verification done, succeed
```
* To refresh the token:
```
#tokenid,username,expire,created,access,comments,disable
"2e07c7a0-76e2-11e9-874a-0242ac110002","zet809","1557904941.85",,,,
[root@briggs01 allien]# curl -X POST -H "Authorization: token …
```
> Add url token based auth section for api-server

- xcat-inventory/xcclient/allien/resources/service.py
- xcat-inventory/xcclient/allien/srvmanager.py
This is the [Mock APIs](https://github.ibm.com/xcat2/task_management/issues/270) for https://github.ibm.com/xcat2/task_management/issues/256
UT:
- apply 3 resources
```
curl -X POST "http://10.6.27.1:5000/api/v2/manager/resmgr" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"capacity\": 3}"
{
"f9b5f8bc-77b5-11e9-93c6-0cc47aea9e02": "c461c022,mid05tor12cn15,mid05tor12cn08"
}
```
- Get all occupied resources
```
curl -X GET "http://10.6.27.1:5000/api/v2/manager/resmgr"
{
"f9b5f8bc-77b5-11e9-93c6-0cc47aea9e02": [
"c461c022",
"mid05tor12cn15",
"mid05tor12cn08"
]
}
```
- Get free pool resources
```
curl -X GET "http://10.6.27.1:5000/api/v2/manager/resmgr?pool=1"
{
"total": 34,
"pool": [
"abcd",
"mid05tor12cn02",
"mid05tor12cn01",
"mid05tor12cn06",
"mid05tor12cn07", …
```
> Mock api for resource mgmt

- xcat-inventory/xcclient/allien/authmanager.py
- xcat-inventory/xcclient/allien/invmanager.py
- xcat-inventory/xcclient/allien/resources/__init__.py
- xcat-inventory/xcclient/allien/resources/auth.py
- xcat-inventory/xcclient/allien/resources/node.py
This PR is for task https://github.ibm.com/xcat2/task_management/issues/135
The modification include:
1. add document for auth related urls
2. move auth related subroutine to authmanager.py
3. add auth_request for rinstall url: /nodes/<node>/_operation
> Update document for /api/v2/auth/x 

- xcat-inventory/xcclient/allien/invmanager.py
- xcat-inventory/xcclient/allien/resources/node.py
- xcat-inventory/xcclient/allien/resources/service.py
Leverage node inventory API to implement the RESTful API
PATH | METHOD | Description | Parameters
------------ | ------------- | --------------- | ------ 
`/system/nodes?type=inventory` | GET | get node inventory | type=inventory
`/system/nodes?` | POST | create node with inventory | 
`/system/nodes/{node}` | GET | get specify node inventory | 
`/system/nodes/{node}` | DELETE | delete specify node | 
`/system/nodes/{node}` | PUT | replace the specify node with new inventory data |
> Inventory api implementation

- xcat-inventory/xcclient/allien/resources/node.py
Give PATH to get all nodes status
to address https://github.ibm.com/xcat2/task_management/issues/188
> fetch node status for all nodes

- xcat-inventory/xcclient/allien/resources/nodehm.py
- xcat-inventory/xcclient/xcatd/client/xcat_cmd_helpers.py
- xcat-inventory/xcclient/xcatd/client/xcat_data.py
- xcat-inventory/xcclient/xcatd/client/xcat_msg.py
- xcat-inventory/xcclient/xcatd/xcat_client.py
For https://github.ibm.com/xcat2/task_management/issues/272
Des:
PATH | METHOD | Description | Parameters
-- | -- | -- | --
/system/nodes/{node}/power | POST | remote control, action will be given in payload |  
UT:
```
[root@byrh07 postscripts]# curl -X POST "http://10.4.41.7:5000/api/v2/system/nodes/byrh08/power" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"action\": \"on\"}"
{
"powerstate": "on"
}
[root@byrh07 postscripts]# curl -X POST "http://10.4.41.7:5000/api/v2/system/nodes/byrh08/power" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"action\": \"off\"}"
{
"powerstate": "off"
}
[root@byrh07 postscripts]# curl -X POST "http://10.4.41.7:5000/api/v2/system/nodes/byrh08/power" -H  "accept: application/json" -H …
```
> add node remote power API

- README.md
* Fix typo for command `yum install ...`
* Mention `api-server` instead of `master` for `api-server` branch.
> Revise README.md for api-server branch

- xcat-inventory/xcclient/allien/authmanager.py
- xcat-inventory/xcclient/allien/invmanager.py
- xcat-inventory/xcclient/allien/resmanager.py
- xcat-inventory/xcclient/allien/resources/__init__.py
- xcat-inventory/xcclient/allien/resources/auth.py
- xcat-inventory/xcclient/allien/resources/security.py
- xcat-inventory/xcclient/allien/resources/service.py
- xcat-inventory/xcclient/allien/srvmanager.py
To address https://github.ibm.com/xcat2/task_management/issues/271
- remove the MOCK API
- using `__TFPOOL-FREE` as free pool, and for occupied:  `__TFPOOL-<username>`
- the tags should be define in `nodelist.comments` as format of `tags=[tag1,tag2,tag2]`
- enhance auth to put username in `g` when using token
- refine some format for python3
> The simple Resmgr API

- xcat-inventory/xcclient/allien/authmanager.py
- xcat-inventory/xcclient/allien/resources/auth.py
1, There is a code error to check the time
```
-        if not check_expire or time.time() >= float(exp):
+        if not check_expire or time.time() < float(exp):
return 0, usr
```
2, Not using embbed `"message": {"message": xxx} `
> Check expire is wrong

- xcat-inventory/xcclient/allien/resources/__init__.py
> add rpower entry in route

- xcat-inventory/xcclient/allien/invmanager.py
- xcat-inventory/xcclient/allien/regexutils.py
for https://github.ibm.com/xcat2/task_management/issues/260
1. Use python to realize the Easy Regular expressions of perl function transRegexAttrs in Table.pm
UT：
1.
```
[root@byrh07 allien]# lsdef -t group bybai
Object name: bybai
members=c910f04x12v04
nichostnamesuffixes.ens4=-ens4
nicips.ens4=|\D+\d+\D+\d+\D+(\d)+\D+(\d+)|30.0.($1).($2/1000+9)|
nicnetworks.ens4=30_0_0_0-255_255_0_0
nictypes.ens4=Ethernet
[root@byrh07 allien]# lsdef c910f04x12v04
Object name: c910f04x12v04
groups=bybai
nichostnamesuffixes.ens4=-ens4
nicips.ens4=30.0.2.9
nicnetworks.ens4=30_0_0_0-255_255_0_0
nictypes.ens4=Ethernet
postbootscripts=otherpkgs
postscripts=syslog,remoteshell,syncfiles
[root@byrh07 allien]# curl -X GET "http://10.4.41.7:5000/api/v2/system/nodes/c910f04x12v04/_detail" -H  "accept: …
```
> add normal regular expression transform for node attribute

- xcat-inventory/xcclient/xcatd/client/xcat_msg.py
For https://github.ibm.com/xcat2/task_management/issues/297
UT:
```
]# curl -X POST "http://127.0.0.1:5000/api/v2/system/nodes/mid05tor12cn03/power" -H  "accept: application/json" -H  "Content-Type: application/json" -H "Authorization: token c997632c-7dfb-11e9-a021-0cc47aea9e02" -d "{  \"action\": \"state\",  \"action_spec\": {}}"
{
"powerstate": "on"
}
]# curl -X POST "http://10.6.27.1:5000/api/v2/system/nodes/mid05tor12cn12/power" -H  "accept: application/json" -H  "Content-Type: application/json" -H "Authorization: token c997632c-7dfb-11e9-a021-0cc47aea9e02" -d "{  \"action\": \"state\",  \"action_spec\": {}}"
{
"message": "Failed to run rpower on mid05tor12cn12 due to: Login to BMC failed: Can't connect to 172.11.139.12 (Connection reset by peer). (code=1)"
}
```
> power API support openbmc

- xcat-inventory/xcclient/inventory/manager.py
Fix some inventory import typos and wording.
> Improve inventory import output messages
